config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  get 'user/reset_password(/:user_id)', to: 'users#reset_password', as: :reset_password

  resources :users, only: %i[create show new destroy]
  patch 'users/:id', to: 'users#update'
  put 'user/:class_id/associate', to: 'users#update', as: :vinculate_user
  patch 'user/:id', to: 'users#update_password'

  resources :class_groups, except: %i[index edit]
  get 'classes/:id', to: 'class_groups#index', as: :admin_classes
  get 'classes/:id/associate', to: 'class_groups#new_user', as: :new_user_class
  get 'classes/:id/users', to: 'class_groups#index_users', as: :users_class

  resources :responses, except: %i[index destroy]
  get 'responses/user/:user_id', to: 'responses#index', as: :responses_board
  delete 'responses/:id', to: 'responses#destroy'
  get 'responses/:id/grade', to: 'responses#show_grade', as: :view_grade

  resources :tasks, except: %i[index destroy]
  get 'tasks/user/:user_id', to: 'tasks#index', as: :tasks_board
  get 'task/:id/responses', to: 'tasks#index_responses', as: :task_responses
  get 'task/response/:id', to: 'tasks#show_response', as: :task_response
  delete 'tasks/:id', to: 'tasks#destroy'
  delete 'task/:id', to: 'tasks#cancel', as: :cancel_task
  delete 'tasks/ajusted/:id', to: 'tasks#remove_ajusted', as: :remove_ajusted
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  enum status: { pending: 0, progress: 1, done: 2, ajusted: 3 }
  has_many :responses
  belongs_to :class_group, optional: false

  validates :title, :class_group_id, :description, :status, :expiration_date, presence: true
  # validates :status, inclusion: { in: [pending, progress, done, ajusted] }
  validates_associated :class_group # Ver
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :restrict_by_authorization
  before_action :restrict_by_profile_admin
  before_action :set_task, only: %i[show index_responses update destroy cancel remove_ajusted]

  # GET /tasks
  # GET /tasks.json
  def index
    @user_id_param = params[:user_id].to_i
    class_groups = ClassGroup.where(user_id: params[:user_id])
    @tasks = Task.where(class_group_id: class_groups)
    check_completed_tasks
    tasks_ajusted?
  end

  def index_responses
    session[:page_back] = params[:page_back] == 'task' ? task_path(@task&.id) : class_group_path(@task&.class_group_id)
    @responses_task = @task&.responses
  end

  def show_response
    @response_task = Response.find_by(id: params[:id])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.status = 0
    @task.active = true

    unless valid_task?
      redirect_to new_task_path
      return
    end

    if @task.save
      handler_notice('Tarefa criada com sucesso!', tasks_board_path(current_user.id))
    else
      handler_notice_error('Erro ao criar tarefa.', new_task_path)
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    return unless can_update?

    if @task.update(task_params)
      generate_responses if @task.progress?

      handler_notice('Tarefa atualizada com sucesso!', tasks_board_path(current_user.id))
    else
      handler_notice_error('Erro ao atualizar tarefa.', task_path(@task))
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    if @task.destroy
      handler_notice('Tarefa excluída com sucesso!', tasks_board_path(current_user.id))
    else
      handler_notic_error('Erro ao excluir tarefa.', tasks_board_path(current_user.id))
    end
  end

  def cancel
    @task.active = false
    if @task.save
      @task.responses.each do |response|
        response.active = false
        unless response.save
          Rails.logger.debug 'erro ao inativar response'
          return
        end
      end

      handler_notice('Tarefa excluída com sucesso!', tasks_board_path(current_user.id))
    else
      handler_notice_error('Erro ao cancelar task', tasks_board_path(current_user.id))
    end
  end

  def remove_ajusted
    @task.active = false
    if @task.save
      handler_notice('Tarefa excluída com sucesso!', tasks_board_path(current_user.id))
    else
      handler_notice_error('Erro ao remover task', tasks_board_path(current_user.id))
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :description, :status, :expiration_date, :class_group_id)
  end

  def generate_responses
    users_group = @task.class_group.users
    users_group.each do |user|
      response = Response.find_or_initialize_by(user_id: user.id, task_id: @task.id, status: 0, active: true)
      Rails.logger.debug 'Error na criacao de response: ', response.errors unless response.save
    end
  end

  def check_completed_tasks
    @tasks.each do |task|
      if task.progress? && task.expiration_date < Time.zone.today
        task.status = 2
        Rails.logger.debug 'Erro ao concluir tarefa automática', task.errors unless task.save
      end
    end
  end

  def valid_task?
    field = nil

    if @task.title.blank?
      field = 'Título inválido'
    elsif @task.expiration_date.blank? || @task.expiration_date < Time.zone.today
      field = 'Data Limite inválida'
    elsif @task.class_group_id.blank?
      field = 'Turma inválida'
    elsif @task.expiration_date > @task.class_group.expiration_date
      field = 'Data Limite inválida. A data deve ser compreendida no período vigente da turma.'
    elsif @task.description.blank?
      field = 'Descrição inválida'
    else
      return true
    end

    flash[:noticeError] = field
    false
  end

  def tasks_ajusted?
    @tasks.each do |task|
      next unless task.done?

      responses_done = task.responses.where(status: 2)
      has_one_unajusted = false
      responses_done.each do |response|
        has_one_unajusted = true if response.grade.blank?
      end

      unless has_one_unajusted
        task.status = 3
        Rails.logger.debug 'Erro ', task.errors unless task.save
      end
    end
  end

  def can_update?
    if !valid_task?
      redirect_to task_path(@task)
      return false
    elsif Date.parse(task_params[:expiration_date]) < @task.expiration_date
      handler_notice_error('A tarefa não pode ser antecipada.', task_path(@task))
      return false
    end

    true
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :class_code %>
    <%= form.number_field :class_code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.date_select :expiration_date %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%# <% if current_user == @user %>
<main class="card-main align-columns">
  <% if current_user.id == @user_id_param %>
    <section class="status-column">
      <div class="status-header">
        <h3 class="status-name">Pendente</h3>
      </div>
      <div class="status-body">
        <% @tasks.each do |task| %>
          <% if task.pending? %>
            <div>
              <div class="div-remove-task">
                <%= link_to "X", task, method: :delete, 
                    class:"remove-task", 
                    data: {confirm: "Tem certeza que deseja remover essa tarefa?"} %>
              </div>
              <div class="div-click-task">
                <a href=<%= task_path(task) %>  >
                  <div class="div-card-task">
                    <span class="card-class status-pending"><%=task.class_group.class_code%></span>
                    <h4 class="card-title"><%=task.title%></h4>
                    <div class="card-footer">
                      <span class="card-date"><%= task.expiration_date.strftime("%d/%m/%Y") %></span>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </section>

    <section class="status-column">
      <div class="status-header">
        <h3 class="status-name">Em Andamento</h3>
      </div>
      <div class="status-body">
      <% @tasks.each do |task| %>
          <% if task.progress? && task.active %>
            <div>
              <div class="div-remove-task">
                <%= link_to "X", cancel_task_path(task), method: :delete, 
                    class:"remove-task", 
                    data: {confirm: "Excluir uma tarefa em andamento excluirá também todo o progesso dos integrantes do grupo. Tem certeza que deseja excluir?"} %>
              </div>
              <div class="div-click-task">
                <a href=<%= task_path(task) %>>
                  <div class="div-card-task">
                    <span class="card-class status-progress"><%=task.class_group.class_code%></span>
                    <h4 class="card-title"><%=task.title%></h4>
                    <div class="card-footer">
                      <span class="card-date"><%=task.expiration_date.strftime("%d/%m/%Y")%></span>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </section>

    <section class="status-column">
      <div class="status-header">
        <h3 class="status-name">Concluído</h3>
      </div>
      <div class="status-body">
      <% @tasks.each do |task| %>
          <% if task.done? && task.active %>
            <div>
              <div class="div-remove-task">
                <%= link_to "X", cancel_task_path(task), method: :delete, 
                    class:"remove-task", 
                    data: {confirm: "Excluir uma tarefa concluída excluirá também toda as respostas do grupo. Tem certeza que deseja excluir?"} %>
              </div>
              <div class="div-click-task">
                <a href=<%= task_path(task) %>>
                  <div class="div-card-task">
                    <span class="card-class status-done"><%=task.class_group.class_code%></span>

                    <h4 class="card-title"><%=task.title%></h4>
                    <div class="card-footer">
                      <span class="card-date"><%=task.expiration_date.strftime("%d/%m/%Y")%></span>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </section>

    <section class="status-column">
      <div class="status-header">
        <h3 class="status-name"><%= "Corrigido" %></h3>
      </div>
      <div class="status-body">
      <% @tasks.each do |task| %>
          <% if task.ajusted? && task.active %>
            <div>
                <div class="div-remove-task">
                  <%= link_to "X", remove_ajusted_path(task), method: :delete, 
                      class:"remove-task", 
                      data: {confirm: "Tem certeza que deseja remover do board?"} %>
                </div>
                <div class="div-click-task">
                  <a href=<%= task_path(task) %>>
                    <div class="div-card-task">
                      <span class="card-class status-not-completed"><%=task.class_group.class_code%></span>
        
                      <h4 class="card-title"><%=task.title%></h4>
                      <div class="card-footer">
                        <span class="card-date"><%=task.expiration_date.strftime("%d/%m/%Y")%></span>
                      </div>
                    </div>
                  </a>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </section>
  <% else %>
    <h1 class='title-page'>Código identificador inválido</h1>
  <% end %>
</main>

app/views/tasks/index_responses.html.erb
<main class="card-main card-table">
  <% unless @task.nil? %>
    <a href=<%= session[:page_back] %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <% end %>
  <div class="content-intern">
    <% if current_user.id == @task&.class_group&.user_id %>
      <h1 class='title-page'>Respostas</h1>

      <table class="table table-bordered table-hover table-page">
        <thead class="header-table-red header-table-font">
          <tr>
            <th>Nome</th>
            <th>Nota</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <tbody class="body-table">
          <% @responses_task.each do |response| %>
            <tr>
              <td class="content-text-table"><%= response.user.name %></td>
              <td><%= response.done? ? response.grade : 'Sem nota' %></td>
              <td><%= link_to 'Visualizar', task_response_path(response.id), class: 'btn btn-default btn-view-item-table', style: 'width: 35%' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  </div>
</main>

app/views/tasks/new.html.erb
<!--<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %> -->

<main class="card-main card-table">
  <a href=<%= admin_classes_path(current_user) %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <div class="content-intern">
   <h1 class='title-page title-task'>Criar Tarefa</h1>
    <%= form_for @task do |form| %>
      <div class="top-panel-create-task">
        <h1 class='title-page title-task'><%= form.text_field :title, placeholder: "Título", class: 'input-title' %></h1>
        
        <section class="section-task-create-task">
          <h4 class="field-task">Data Limite:  </h4>
          <span class="span-task"><%= form.date_field :expiration_date, class: 'data-field-expiration' %></span>
        </section>

        <%= form.collection_select :class_group_id, ClassGroup.where(user_id: current_user), :id, :class_code, {} , class: 'drop-class-code' %>
      </div>

      <section class="description-task">
        <h4 class="item-description">Descrição:</h4>
        <h3 class="description-task-text item-description"><%= form.text_area :description, class: 'input-text-task' %></h3>
      </section>

      <section class="content-body-create-task">      
        <section class="section-create-task">
          <%= form.submit 'Criar', class: 'btn-new-item-create-task btn-create-task' %>
        </section>
      </section>  
    <% end %>
  </div>
</main>

app/views/tasks/show.html.erb
<main class="card-main card-table">
  <a href='<%= tasks_board_path(current_user.id) %>' data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <div class="content-intern">
    <% if current_user.id == @task&.class_group&.user_id %>
      <%= form_for @task do |form| %>
        <div class="top-panel">
          <h1 class='title-page title-task'><%= form.text_field :title, class: 'input-title', disabled: @task.ajusted? || @task.done? %></h1>
          
          <section class="section-task">
            <h4 class="field-task">Entregar até:  </h4>
            <span class="span-task"><%= form.date_field :expiration_date, class: 'data-field-expiration', disabled: @task.ajusted? || @task.done? %></span>
          </section>

          <section class="section-task">
            <h4 class="field-task">Professor:  </h4>
            <span class="span-task"><%= @task.class_group.user.name %></span>
          </section>

          <section class="section-task">
            <h4 class="field-task">Disciplina:  </h4>
            <span class="span-task"><%= @task.class_group.discipline %></span>
          </section>

          <section class="section-task">
            <span class="card-class status-not-completed code-class"><%= @task.class_group.class_code %></span>
          </section>
        </div>

        <section class="description-task">
          <h4 class="item-description">Descrição:</h4>
          <h3 class="description-task-text item-description"><%= form.text_area :description, class: 'input-text-task', disabled: @task.ajusted? || @task.done? %></h3>
        </section>

        <section class="content-body">
          <% unless @task.done? || @task.ajusted? %>
            <section class="section-alterar-status" style=<%= @task.progress? ? 'margin-left:38em' : '' %>>
              <% if @task.pending? %>
                <%= form.select :status, options_for_enum(@task, :status, 2), {}, class: 'status-task' %>
              <% end %>
              <%= form.submit 'Alterar', class: 'btn-new-item btn-alterar', style: @task.progress? ? 'margin-top: 2.5em;' : '' %>
            </section>
          <% end %>

          <section class="section-response-user" style=<%= @task.pending? ? 'display:none' : '' %>>
            <%= link_to 'Visualizar Respostas', task_responses_path(@task.id, :page_back => 'task'), class: 'btn-new-student upload-task text-button-task' %>
          </section>
        </section>    
      <% end %>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  </div>
</main>

app/views/tasks/show_response.html.erb
<main class="card-main card-table">
  <% unless @response_task.nil? %>
    <a href='<%= task_responses_path(@response_task.task_id) %>' data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <% end %>
  <div class="content-intern">
    <% if current_user.id == @response_task&.task&.class_group&.user_id %>
      <%= form_with(model: @response_task, local: true) do |form| %>
        <div class="top-panel">
          <h1 class='title-page title-task'><%= @response_task.task.title %></h1>

          <section class="section-task">
            <h4 class="field-task">Aluno:  </h4>
            <span class="span-task"><%= @response_task.user.name %></span>
          </section>

          <section class="section-task">
            <h4 class="field-task">Disciplina:  </h4>
            <span class="span-task"><%= @response_task.task.class_group.discipline %></span>
          </section>

          <section class="section-task">
            <span class="card-class status-not-completed code-class"><%= @response_task.task.class_group.class_code %></span>
          </section>
        </div>

        <section class="response">
          <section class="description-task response-description-task">
            <h4>Resposta:</h4>
            <h3 class="description-task-text"><%= @response_task.response_annotation %></h3>
          </section>

          <section class="upload-response response-upload-task">
            <% if @response_task&.response_value.present? %>
              <a href=<%= rails_blob_path(@response_task.response_value, disposition: "attachment") %> data-toggle="tooltip" title="Download Resposta"><%= image_tag('download.png', id: "download", class: "icon-page") %></a>
              <span>Arquivo de Resposta: <%= @response_task.response_value.filename %></span>
            <% end %>
          </section>
        </section>

        <section class="content-body-response">
          <section class="response-user-task">
            <%= form.text_field :observation_responsible, class:"annotation-task observation-responsible", placeholder: "Escreva suas observações.." %>
          </section>
        
          <section class="section-alterar-status" style="margin-top: 0;">
            <%= form.label :nota, style: 'font-size: 19px'%>
            <%= form.number_field :grade, step:0.01, class:"status-task" %>
            <%= form.submit 'Avaliar', class: ' btn-alterar-response btn-new-item btn-alterar' %>
          </section>
        </section>
      <% end %>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  </div>
</main>