config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  get 'user/reset_password(/:user_id)', to: 'users#reset_password', as: :reset_password

  resources :users, only: %i[create show new destroy]
  patch 'users/:id', to: 'users#update'
  put 'user/:class_id/associate', to: 'users#update', as: :vinculate_user
  patch 'user/:id', to: 'users#update_password'

  resources :class_groups, except: %i[index edit]
  get 'classes/:id', to: 'class_groups#index', as: :admin_classes
  get 'classes/:id/associate', to: 'class_groups#new_user', as: :new_user_class
  get 'classes/:id/users', to: 'class_groups#index_users', as: :users_class

  resources :responses, except: %i[index destroy]
  get 'responses/user/:user_id', to: 'responses#index', as: :responses_board
  delete 'responses/:id', to: 'responses#destroy'
  get 'responses/:id/grade', to: 'responses#show_grade', as: :view_grade

  resources :tasks, except: %i[index destroy]
  get 'tasks/user/:user_id', to: 'tasks#index', as: :tasks_board
  get 'task/:id/responses', to: 'tasks#index_responses', as: :task_responses
  get 'task/response/:id', to: 'tasks#show_response', as: :task_response
  delete 'tasks/:id', to: 'tasks#destroy'
  delete 'task/:id', to: 'tasks#cancel', as: :cancel_task
  delete 'tasks/ajusted/:id', to: 'tasks#remove_ajusted', as: :remove_ajusted
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :responses
  has_and_belongs_to_many :class_groups
  has_secure_password

  attr_accessor :password, :password_confirm

  enum profile: { standard: 0, admin: 1 }
  # validates :profile, inclusion: { in: [standard, admin] }

  VALID_EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i.freeze
  # pesquisar solucao depois
  # validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  validates :password_digest, :profile, :name, :email, presence: true

  def confirm_password?(confirm)
    @password.eql?(confirm)
  end

  def self.unique_email?(email)
    user = User.find_by(email: email)

    return true if user.nil?

    false
  end

  def validate_user?
    return 'Dados de usuário inválidos.' if !valid? || @password.blank?
    return 'Esse email já existe.' unless User.unique_email?(email)
    return 'A senha precisa ser igual à sua confirmação.' unless confirm_password?(password_confirm)

    nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :restrict_by_authorization, only: %i[update destroy]
  before_action :authorized, only: [:show]
  before_action :set_user , only: %i[destroy update_password]
  before_action :load_enviroments_vars, only: %i[reset_password]

  # GET /users/1
  # GET /users/1.json
  def show
    @responses_user = Response.all.where(user_id: params[:id])
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    return if redirected_logged

    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_to_be_created)

    error = @user.validate_user?

    if error.nil? && @user.save
      handler_notice('Usuário cadastrado com sucesso!', login_path)
    else
      handler_notice_error(error, new_user_path)
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    puts 'ENTROU NO UPDATE USER'
    return vinculate_user unless params[:vincular].nil?

    update_password
  end

  def vinculate_user
    puts 'PARAMS ', params
    registered_user = User.find_by(email: params.dig(:user, :email))

    class_id = session[:class_id_vinculate]
    puts 'CLASSGH ', session[:class_id_vinculate]
    
    if registered_user.nil?
      handler_notice_error('Usuário inexistente.', new_user_class_path(class_id))
    elsif registered_user.admin?
      handler_notice_error('Este usuário não pode ser vinculado à turma devido ao tipo de perfil que possui.', new_user_class_path(class_id))
    else
      class_associate = registered_user.class_groups.find_by(id: class_id)

      if class_associate.nil?
        associate_user(registered_user, class_id)
      else
        handler_notice_error('Este usuário já está vinculado à turma.', new_user_class_path(class_id))
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    remove_user_associations
    @user.destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  def reset_password
    return unless valid_token?

    # Armazenando para reacessar página em caso de erro
    session[:token] = params[:reset]
    session[:expire] = params[:expire]
    session[:user] = params[:reset]
    @user = match_user(session[:user])
  end

  def update_password
    return unless valid_password?(reset_params)

    @user = match_user(session[:user])
    @user.password_digest = encrypt(params.dig(:user, :password))
    if @user.save
      handler_notice('Senha resetada com sucesso!', login_path)
    else
      puts 'Erro ao resetar senha', @user.errors
      redirect_to_reset_password
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password)
  end

  def reset_params
    params.require(:user).permit(:password, :password_confirm)
  end

  def valid_password?(params_validate)
    if params_validate[:password].present?
      flash[:noticeError] = 'As senhas devem ser iguais.' if params_validate[:password] != params_validate[:password_confirm]
    else
      flash[:noticeError] = 'A senha deve ser preenchida.'
    end

    return true if flash[:noticeError].nil?
    redirect_to_reset_password
    false
  end

  def user_to_be_created
    {
      name: params.dig(:user, :name),
      registration: params.dig(:user, :registration),
      profile: params.dig(:user, :profile),
      email: params.dig(:user, :email),
      password: params.dig(:user, :password),
      password_confirm: params.dig(:user, :password_confirm),
      password_digest: BCrypt::Password.create(params.dig(:user, :password))
    }.to_hash
  end

  def associate_user(user, class_id)
    class_group = ClassGroup.find_by(id: class_id)
    user.class_groups << class_group

    assign_group_tasks(class_group, user.id)

    handler_notice('Usuário vinculado com sucesso.', class_group_path(class_id))
  end

  def remove_user_associations
    if @user.admin?
      classes = ClassGroup.where(user_id: @user.id)
      classes.each do |cgroup|
        cgroup.tasks.each do |task|
          task.responses.destroy_all
          task.destroy
        end

        cgroup.users.clear
        cgroup.destroy
      end
    else
      @user.responses.destroy_all
      @user.class_groups.clear
    end
  end

  def assign_group_tasks(group, user_id)
    group.tasks.each do |task|
      if task.progress?
        response = Response.new(user_id: user_id, task_id: task.id, status: 0, active: true)
        puts "Error na criacao de response: ", response.errors unless response.save
      end
    end
  end

  def match_user(token)
    token_compare = BCrypt::Password.new(token)
    User.all.each do |user|
      sentence_compare = user.name + ENV["SEED"] + user.profile

      if token_compare == sentence_compare
        return user
      end
    end

    nil
  end

  def valid_token?
    expire = params[:expire].to_i
    intervalo = Time.now.to_i - expire
    return true if intervalo / 60 <= 10 # não resetar se tiver mais de 10 min que foi gerado o token

    flash[:noticeError] = "token expirado"
    false
  end

  def redirect_to_reset_password
    redirect_to reset_password_path(@user, :expire => session[:expire], :reset => session[:token])
  end

  def encrypt(sentence)
    #colocar exception
    BCrypt::Password.create(sentence)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile %>
    <%= form.number_field :profile %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :registration %>
    <%= form.text_field :registration %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Name</th>
      <th>Registration</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.profile %></td>
        <td><%= user.name %></td>
        <td><%= user.registration %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<main class="card-main card-table">
  <a href=<%= login_path %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <% if flash[:noticeError] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:noticeError] %>
    </div>
  <% end %>
  <div class="content-intern">
    <h1 class='title-page title-task'>Cadastrar Usuário</h1>
    <div class="form-group-register">
      <%= form_for @user do |form| %>
        <div style="width: 70%; margin: auto; margin-top: 2em;">
          <div style="width: 100%; margin: auto;">
            <%= form.label 'Nome' %>
            <%= form.text_field :name, class:"form-control text-field", style: 'margin-top: 0;', placeholder: "Qual seu nome??" %>

            <div style="display: inline-block; width: 100%; margin-top: 1em;">
              <div style="display: inline-block; vertical-align: bottom; width: 48%">
                <%= form.label 'Matrícula' %>
                <%= form.text_field :registration, class:"form-control text-field", style: 'margin-top: 0;', placeholder: "Tem matrícula? Qual?" %>
              </div>

              <div style="display: inline-block; margin-left: 2em; width: 48%">
                <%= form.label 'Tipo de usuário' %>
                <%= form.select :profile, options_for_enum(@user, :profile, 0), {}, class:"form-control text-field select-profile", style: 'margin-top: 0em;' %>
              </div>
            </div>
          </div>

          <div style="margin-top: 3em; width: 100%;">
            <%= form.label :email %>
            <%= form.email_field :email, class:"form-control text-field", style: 'margin-top: 0;', placeholder: "Digite seu email" %>
          </div>

          <div style=" width: 100%;  margin-top: 1em;">
            <div style="display: inline-block; vertical-align: bottom; width: 48%">
              <%= form.label 'Senha' %>
              <%= form.password_field :password, class:"form-control text-field", style: 'margin-top: 0;', placeholder: "Qual vai ser a senha?" %>
            </div>

            <div style="display: inline-block; margin-left: 2em; width: 48%">
              <%= form.label 'Confirmação de senha' %>
              <%= form.password_field :password_confirm, class:"form-control text-field", style: 'margin-top: 0;', placeholder: "Tem certeza da senha? Repita." %>
            </div>
          </div>
          
          <div style="margin: auto; width: 85%;">
            <%= form.submit "Cadastrar", class:"btn btn-danger btn-login", style: 'margin-top: 3em;' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/users/reset_password.html.erb
<main class="card-main card-table">
  <!-- ver pra ao clicar no voltar, desvalidar token -->
  <a href=<%= login_path %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <div class="content-intern">

  <% if flash[:noticeError].nil? || flash[:noticeError] != "token expirado" %>
    <h1 class='title-page'>Resetar Senha</h1>
    <div class="reset-password">
      <%= form_with(model: @user, local: true) do |form| %>
        <%= form.password_field :password, class:"form-control text-field", placeholder: "Digite a nova senha" %>
        <%= form.password_field :password_confirm, class:"form-control text-field", placeholder: "Confirme a senha" %>
        <%= form.submit 'Resetar', class: 'btn-reset btn-new-item' %>
      <% end %>
    </div>
  <% else %>
    <h1>Token expirado. Solicite novamente a alteração da senha.</h1>
    <% flash[:noticeError] = nil %>
  <% end %>
  </div>
</main>

app/views/users/show.html.erb
<main class="card-main card-table">
  <a href='<%= current_user.admin? ? tasks_board_path(current_user.id) : responses_board_path(current_user.id) %>' data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <div class="content-intern">
    <% if current_user.id == @user.id %>
      <h1 class='title-my-account'>Minha Conta</h1>
      <div style="display:inline-block; margin-top: 3em; margin-left: 10.5em;">
        <p class="infos-my-account">
          <strong>Perfil:</strong>
          <%= @user.profile %>
        </p>

        <p class="infos-my-account">
          <strong>Nome:</strong>
          <%= @user.name %>
        </p>

        <p class="infos-my-account">
          <strong>Matrícula:</strong>
          <%= @user.registration %>
        </p>

        <p class="infos-my-account">
          <strong>Email:</strong>
          <%= @user.email %>
        </p>

        <p class="infos-my-account">
          <strong>Criado em:</strong>
          <%= @user.created_at.strftime("%d/%m/%Y") %>
        </p>
      </div>
      <div style="height: 65vh; margin: auto;">
        <%= link_to 'Excluir Conta', @user, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esta conta? Isso irá apagar todo o progresso realizado' }, class: 'btn-remove-account' %>
      </div>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  </div>
</main>