config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  get 'user/reset_password(/:user_id)', to: 'users#reset_password', as: :reset_password

  resources :users, only: %i[create show new destroy]
  patch 'users/:id', to: 'users#update'
  put 'user/:class_id/associate', to: 'users#update', as: :vinculate_user
  patch 'user/:id', to: 'users#update_password'

  resources :class_groups, except: %i[index edit]
  get 'classes/:id', to: 'class_groups#index', as: :admin_classes
  get 'classes/:id/associate', to: 'class_groups#new_user', as: :new_user_class
  get 'classes/:id/users', to: 'class_groups#index_users', as: :users_class

  resources :responses, except: %i[index destroy]
  get 'responses/user/:user_id', to: 'responses#index', as: :responses_board
  delete 'responses/:id', to: 'responses#destroy'
  get 'responses/:id/grade', to: 'responses#show_grade', as: :view_grade

  resources :tasks, except: %i[index destroy]
  get 'tasks/user/:user_id', to: 'tasks#index', as: :tasks_board
  get 'task/:id/responses', to: 'tasks#index_responses', as: :task_responses
  get 'task/response/:id', to: 'tasks#show_response', as: :task_response
  delete 'tasks/:id', to: 'tasks#destroy'
  delete 'task/:id', to: 'tasks#cancel', as: :cancel_task
  delete 'tasks/ajusted/:id', to: 'tasks#remove_ajusted', as: :remove_ajusted
end

app/models/class_group.rb
# frozen_string_literal: true

class ClassGroup < ApplicationRecord
  has_many :tasks
  has_and_belongs_to_many :users
  belongs_to :user, optional: false # Verificar depois

  validates :discipline, :class_code, :expiration_date, presence: true
end

app/controllers/class_groups_controller.rb
class ClassGroupsController < ApplicationController
  before_action :restrict_by_authorization
  before_action :restrict_by_profile_admin
  before_action :set_class_group, only: %i[show new_user index_users edit update destroy]
  before_action :clear_session_vinculate, only: [:show]

  # GET /class_groups
  # GET /class_groups.json
  def index
    @user_id_param = params[:id].to_i
    class_groups_user = ClassGroup.where(user_id: @user_id_param)
    check_class_groups_validity(class_groups_user)
    @class_groups = class_groups_user.where(active: true)
  end

  def index_users; end

  # GET /class_groups/1
  # GET /class_groups/1.json
  def show; end

  # GET /class_groups/new
  def new
    @class_group = ClassGroup.new
  end

  # POST /class_groups
  # POST /class_groups.json
  def create
    @class_group = ClassGroup.new(class_group_params)

    return unless valid_group?

    @class_group.active = true
    @class_group.user_id = session[:user_id] # Verificar sobre passagem de id do user na rota

    if @class_group.save
      handler_notice('Turma cadastrada com sucesso!', admin_classes_path(current_user))
    else
      flash[:noticeError] = 'Erro ao cadastrar tarefa.'
      render :new
    end
  end

  # DELETE /class_groups/1
  # DELETE /class_groups/1.json
  def destroy
    return unless remove_associates
    return unless remove_tasks
    return unless @class_group.destroy

    handler_notice('Turma removida com sucesso!', admin_classes_path(current_user))
  end

  def new_user
    @user.email = nil
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_class_group
    @class_group = ClassGroup.find_by(id:params[:id])
  end

  # Only allow a list of trusted parameters through.
  def class_group_params
    params.require(:class_group).permit(:responsible, :discipline, :class_code, :active, :expiration_date)
  end

  def remove_associates
    @class_group.tasks.each do |task|
      Response.destroy_by(task_id: task.id)
    end

    @class_group.users.clear
  end

  def remove_tasks
    @class_group.tasks.destroy_all
  end

  def valid_group?
    unless @class_group.discipline.present? || @class_group.class_code.present?
      handler_notice_error("Todos os campos devem ser preenchidos.", new_class_group_path)
      return false
    end

    if @class_group.expiration_date < Date.today
      handler_notice_error('Data Inválida.', new_class_group_path)
      return false
    end

    group_equal = ClassGroup.find_by(class_code: @class_group.class_code)
    if !group_equal.nil? && group_equal.active
      handler_notice_error('Já existe uma turma ativa com esse código.', new_class_group_path)
      return false
    end

    true
  end

  def check_class_groups_validity(class_groups)
    class_groups.each do |group|
      if group.active && group.expiration_date < Date.today
        group.active = false
        puts 'Erro ao desativar turma' unless group.save
      end
    end
  end

  def clear_session_vinculate
    session[:class_id_vinculate] = nil
  end
end

app/helpers/class_groups_helper.rb
# frozen_string_literal: true

module ClassGroupsHelper
end

app/views/class_groups/_form.html.erb
<%= form_with(model: class_group, local: true) do |form| %>
  <% if class_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_group.errors.count, "error") %> prohibited this class_group from being saved:</h2>

      <ul>
        <% class_group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="top-panel-create-class">
    <div class="field field-class field-discipline">
      <%= form.label "Disciplina" %>
      <%= form.text_field :discipline, class: 'discipline-class' %>
    </div>

    <div class="field field-class">
      <%= form.label "Código Turma" %>
      <%= form.text_field :class_code, class: 'discipline-class' %>
    </div>

    <div class="field field-class">
      <%= form.label "Data Expiração" %>
      <%= form.date_field :expiration_date, class: 'data-field-expiration' %>
    </div>
  </div>

  <div class="actions" style="display: flex; margin-top: 10em;">
    <%= form.submit 'Criar', class: 'btn-new-item', style: 'margin: auto; padding-left: 4em;' %>
  </div>
<% end %>

app/views/class_groups/index.html.erb
<main class="card-main card-table">
  <a href=<%= tasks_board_path(current_user.id) %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <div class="content-intern">
    <% if current_user.id == @user_id_param %>
      <h1 class='title-page'>Turmas</h1>

      <table class="table table-bordered table-hover table-page">
        <thead class="header-table header-table-font">
          <tr>
            <th>Turma</th>
            <th>Disciplina</th> 
            <th>Data Encerramento</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody class="body-table">
          <% @class_groups.each do |class_group| %>
            <tr>
              <td><%= class_group.class_code %></td>
              <td class="content-text-table"><%= class_group.discipline %></td>
              <td><%= class_group.expiration_date.strftime("%d/%m/%Y") %></td>
              <td><%= link_to 'Visualizar', class_group, class: 'btn btn-default btn-view-item-table' %></td>
              <td><%= link_to 'Remover', class_group, method: :delete, data: { confirm: 'Tem certeza que deseja remover ?' }, class:"btn btn-danger btn-tables" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <div class="btns-content">
        <%= link_to 'Criar Turma', new_class_group_path, class: 'btn-new-student btn-new-iten-table' %>
        <%= link_to 'Criar Tarefa', new_task_path, class: 'btn-new-item-task-class btn-new-iten-table btn-new-task-class' %>
      </div>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  </div>
</main>

app/views/class_groups/index_users.html.erb
<main class="card-main card-table">
  <% unless @class_group.nil? %>
    <a href=<%= class_group_path(@class_group.id) %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <% end %>
  <div class="content-intern">
    <% if current_user.id == @class_group&.user_id %>
      <h1 class='title-page'>Integrantes</h1>

      <table class="table table-bordered table-hover table-page">
        <thead class="header-table-red header-table-font">
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Matrícula</th>
          </tr>
        </thead>

        <tbody class="body-table">
          <% @class_group.users.each do |user| %>
            <tr>
              <td class="content-text-table"><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.registration %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  </div>
</main>

app/views/class_groups/new.html.erb
<main class="card-main card-table">
  <a href=<%= admin_classes_path(current_user.id) %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <div class="content-intern">
   <h1 class='title-page title-task'>Criar Turma</h1>

    <%= render 'form', class_group: @class_group %>
  </div>
</main>

app/views/class_groups/new_user.html.erb
<main class="card-main card-table">
  <% unless @class_group.nil? %>
    <a href=<%= class_group_path(@class_group.id) %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <% end %>
  <div class="content-intern">
    <% if current_user.id == @class_group&.user_id %>
      <h1 class='title-page'>Vincular Aluno</h1>
      <%= form_with(model: @user, local: true) do |form| %>
        <%= form.email_field :email, class:"form-control text-field text-email-associate", placeholder: "email do aluno.." %>
        <% session[:class_id_vinculate] = @class_group.id %>
        <%= form.submit 'Vincular', name: 'vincular', class_id: 'aqui', class: 'btn-associate btn-new-item' %>
      <% end %>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  </div>
</main>

app/views/class_groups/show.html.erb
<main class="card-main card-table">
  <a href=<%= admin_classes_path(current_user.id) %> data-toggle="tooltip" title="Voltar"><%= image_tag('back.png', id: "back", class: "icon-page") %></a>
  <div class="content-intern">
    <% if current_user.id == @class_group&.user_id %>
      <h1 class='title-page'>Turma: <%=@class_group.class_code%></h1>

      <table class="table table-bordered table-hover table-page">
        <thead class="header-table header-table-font">
          <tr>
            <th>Tarefa</th>
            <th>Data Limite</th> 
            <th>Status</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <tbody class="body-table">
          <% @class_group.tasks.each do |task| %>
            <tr>
              <td class="content-text-table"><%= task.title %></td>
              <td><%= task.expiration_date.strftime("%d/%m/%Y") %></td>
              <td><%= value_enum_current(task.status) %></td>
              <td><%= link_to 'Ver Respostas', task_responses_path(task.id, :page_back => 'class'), class: 'btn btn-default btn-view-item-table', style: 'width: 35%' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <div class="btns-content content-btn-classes">
        <%= link_to 'Visualizar Integrantes', users_class_path(@class_group.id), class: 'btn-new-student upload-task text-button-task' %>
        <%= link_to 'Vincular Usuário', new_user_class_path(@class_group.id), class: 'btn-associate-user' %>
      </div>
    <% else %>
      <h1 class='title-page'>Código identificador inválido</h1>
    <% end %>
  <div>
</main>