config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  get 'user/reset_password(/:user_id)', to: 'users#reset_password', as: :reset_password

  resources :users, only: %i[create show new destroy]
  patch 'users/:id', to: 'users#update'
  put 'user/:class_id/associate', to: 'users#update', as: :vinculate_user
  patch 'user/:id', to: 'users#update_password'

  resources :class_groups, except: %i[index edit]
  get 'classes/:id', to: 'class_groups#index', as: :admin_classes
  get 'classes/:id/associate', to: 'class_groups#new_user', as: :new_user_class
  get 'classes/:id/users', to: 'class_groups#index_users', as: :users_class

  resources :responses, except: %i[index destroy]
  get 'responses/user/:user_id', to: 'responses#index', as: :responses_board
  delete 'responses/:id', to: 'responses#destroy'
  get 'responses/:id/grade', to: 'responses#show_grade', as: :view_grade

  resources :tasks, except: %i[index destroy]
  get 'tasks/user/:user_id', to: 'tasks#index', as: :tasks_board
  get 'task/:id/responses', to: 'tasks#index_responses', as: :task_responses
  get 'task/response/:id', to: 'tasks#show_response', as: :task_response
  delete 'tasks/:id', to: 'tasks#destroy'
  delete 'task/:id', to: 'tasks#cancel', as: :cancel_task
  delete 'tasks/ajusted/:id', to: 'tasks#remove_ajusted', as: :remove_ajusted
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Attention Class</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class=<%= class_name("container") %>>
      <% if logged_in? && !current_page?(login_path) %>
        <%= nav_bar brand: "Attention Class", brand_link: current_user.admin? ? tasks_board_path(current_user.id) : responses_board_path(current_user.id)  do %>
          <%= menu_group do %>
            <% if current_user.admin? %>
              <%= menu_item "Turmas", admin_classes_path(:id => current_user ), class: "nav-menu-item" %>
              <%# <%= menu_item "Tarefas", root_url, class: "nav-menu-item" %>
            <% end %>
              <%= menu_item "Minha Conta", user_path(:id => current_user ), class: "nav-menu-item" %>
          <% end %>
          <a href=<%= sessions_path %> data-method="delete" data-toggle="tooltip" title="Sair">
            <%= image_tag('logout.png', id: "logouticon", class: "icon-page logouticon navbar-form navbar-right") %>
          </a>
        <% end %>
      <% end %>

      <% if !current_user.nil? && !(current_page?(login_path) || current_page?(signup_path)) %>
        <% if flash[:notice] %>
          <div class="alert alert-success" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:noticeError] && flash[:noticeError] != "token expirado" %>
          <div class="alert alert-danger" role="alert">
            <%= flash[:noticeError] %>
          </div>
        <% end %>
      <% end %>

      <div class=<%= main_class() %>>
        <%= yield %>
      </div>
    </div>
  </body>
</html>